# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernal <- function(dx) {
    .Call('_SSIndex3_kernal', PACKAGE = 'SSIndex3', dx)
}

M2 <- function(beta, Z, T2, C2, Y2, h, ht) {
    .Call('_SSIndex3_M2', PACKAGE = 'SSIndex3', beta, Z, T2, C2, Y2, h, ht)
}

shapeFun3 <- function(n, m, midx, tij, yi, xb, x, t, h, w, med, result) {
    .Call('_SSIndex3_shapeFun3', PACKAGE = 'SSIndex3', n, m, midx, tij, yi, xb, x, t, h, w, med, result)
}

size <- function(n, xr, mFhat, w) {
    .Call('_SSIndex3_size', PACKAGE = 'SSIndex3', n, xr, mFhat, w)
}

